const redis = require('redis')

const client = redis.createClient()

client.hset('metaparser_analytics', 'metaparser_aviaparser', JSON.stringify([
        "parse_date",
        "parse_time",
        "class",
        "direction",
        "departure",
        "return",
        "carrier_fw",
        "carrier_bw",
        "flights",
        "direct",
        "channel",
        "agent",
        "fics",
        "fare",
        "taxes",
        "com%",
        "com_abs",
        "t%",
        "dis/mar",
        "nf%",
        "nc%",
        "nt%",
        "sale",
        "ldiff",
        "max diff",
        "need diff%",
        "need diff",
        "nnf%",
        "nnc%",
        "nnt%",
        "fake/no fare",
        "hidden",
        "ota1",
        "ota2",
        "ota3",
        "ota1n",
        "ota2n",
        "ota3n",
        "count",
        "mdm_markup",
        "pmode",
        "pos_offer",
        "carrier_fd_valid",
        "carrier_bw_valid",
        "flightnumbers",
        "ott_place",
        "ott_price"
    ]), function(err){
	console.log(err || 'ok')
})